
#ifndef MAINMENU_ACTIONS_H
#define MAINMENU_ACTIONS_H

enum MenuActions{
	NULL_ACTION,
	GO_TO_EDITOR_STATE,
	GO_TO_MAIN_MENU,
	GO_TO_AI_TEST,
	GO_TO_RACING_STATE,
	GO_TO_NETWORK_TEST,
	GO_TO_BLUEPRINT_EDITOR,

	INCREASE_PLAYERS,
	DECREASE_PLAYERS,

	NEXT_UI_ELEMENT,
	PREVIOUS_UI_ELEMENT,
	ACTIVATE_UI_ELEMENT,

	TEST_AUDIO,
};

#endif
