// Emil Hedemalm
// 2013-08-10

#ifndef NETWORK_STATUS_H
#define NETWORK_STATUS_H

enum networkStati{
    NETWORK_STATUS_NULL,
    NETWORK_STATUS_INITIALIZING,
    NETWORK_STATUS_IDLE,
    NETWORK_STATUS_HOSTING,
    NETWORK_STATUS_JOINING,
    NETWORK_STATUS_HOSTED,
    NETWORK_STATUS_JOINED,
    NETWORK_STATUS_ERROR,
};

/*
enum networkStatus {
	NETWORK_STATUS_NULL,
	NETWORK_STATUS_INITIALIZING,
	NETWORK_STATUS_INITIALIZED,
	NETWORK_STATUS_SERVER,
	NETWORK_STATUS_CLIENT,
	NETWORK_STATUS_ERROR
};
*/
#endif
